# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
# Development Tools:
lune = "lune-org/lune@0.10.4"

# Project Sync Tools: (Only one is required)
# rojo = "rojo-rbx/rojo@7.6.1"
argon = "argon-rbx/argon@2.0.27"

# Wally Tools:
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.6.2"