[package]
name = "radra/maze-simulation"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
fusion = "elttob/fusion@0.3.0"
charm = "littensy/charm@0.10.0"
CharmSync = "littensy/charm-sync@0.3.0"
Remo = "littensy/remo@1.5.3"
DocumentService = "anthony0br/documentservice@1.2.2"
t = "osyrisrblx/t@3.1.1"

[dev-dependencies]
testez = "roblox/testez@0.4.1"
ui-labs = "pepeeltoro41/ui-labs@2.4.2"

[server-dependencies]
Cmdr = "evaera/cmdr@^1.9.0"
