[package]
name = "radra/maze-simulation"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
fusion = "elttob/fusion@0.3.0"
charm = "littensy/charm@0.10.0"
CharmSync = "littensy/charm-sync@0.3.0"
Remo = "littensy/remo@1.5.3"
